import { useEffect, useRef, useState } from 'react'
import { Link, useSearchParams } from 'react-router-dom'
import Seo from '../components/Seo.jsx'
import { createWebLead } from '../hooks/useWebLeads.js'
import { trackEvent } from '../lib/analytics.js'

const included = ['Una página web de hasta seis secciones', 'Diseño para celulares, tablets y computadoras', 'Presentación del negocio y sus servicios', 'Botón de WhatsApp normal, llamada o Instagram', 'Ubicación o Google Maps', 'Formulario de contacto', 'SEO técnico inicial', 'Publicación inicial en Netlify o Vercel', 'Conexión de un dominio que ya tengas', 'Una ronda de correcciones', 'Entrega en 72 horas tras recibir materiales y primer pago']
const excluded = ['Compra o renovación del dominio', 'Diseño profesional de logo', 'Tienda virtual', 'Sistema de reservas', 'Panel administrativo', 'Producción de fotografías', 'Redacción extensa', 'Integraciones avanzadas', 'Modificaciones ilimitadas', 'Mantenimiento mensual permanente']
const custom = ['Tiendas virtuales', 'Catálogos administrables', 'Reservas o turnos', 'Pagos en línea', 'Panel administrativo', 'Formularios y flujos avanzados', 'Integraciones externas', 'Automatizaciones', 'Varios idiomas', 'Más páginas o secciones', 'Diseño completamente personalizado', 'Funciones con inteligencia artificial']
const faqs = [
  { q: '¿El precio incluye dominio?', a: 'No. El dominio se cotiza y paga por separado según nombre, extensión, disponibilidad, proveedor y renovación anual. Siempre que sea posible se registra bajo el control del cliente.' },
  { q: '¿El hosting está incluido?', a: 'Incluimos la configuración y publicación inicial en Netlify o Vercel. Puede iniciarse con un plan gratuito sujeto a sus límites; si luego se necesita un plan pago, el costo será informado y asumido por el cliente.' },
  { q: '¿Cuándo se entrega?', a: 'En 72 horas después de recibir todos los materiales necesarios y el primer pago.' },
]
const initial = { full_name: '', business_name: '', city: '', business_type: '', contact_phone: '', email: '', project_type: 'web_express', needs_description: '', preferred_contact: 'whatsapp', consent: false, website: '' }

export default function WebsParaguay() {
  const [params] = useSearchParams()
  const [form, setForm] = useState(() => ({ ...initial, project_type: params.get('project') === 'custom' ? 'custom_project' : 'web_express' }))
  const [state, setState] = useState('idle')
  const started = useRef(Date.now())
  const submitted = useRef(false)
  useEffect(() => { trackEvent('webs_paraguay_view') }, [])
  const jsonLd = [
    { '@context': 'https://schema.org', '@type': 'Organization', name: 'CVitae Studio' },
    { '@context': 'https://schema.org', '@type': 'Service', name: 'Web Express', areaServed: { '@type': 'Country', name: 'Paraguay' }, offers: { '@type': 'Offer', price: '550000', priceCurrency: 'PYG', description: 'Precio inicial. Dominio no incluido; proyectos personalizados cotizados por separado.' } },
    { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faqs.map(item => ({ '@type': 'Question', name: item.q, acceptedAnswer: { '@type': 'Answer', text: item.a } })) },
  ]
  const change = e => setForm(value => ({ ...value, [e.target.name]: e.target.type === 'checkbox' ? e.target.checked : e.target.value }))
  async function submit(e) {
    e.preventDefault()
    if (submitted.current || form.website || Date.now() - started.current < 2500) return setState('error')
    if (!form.consent) return setState('error')
    setState('sending')
    const clean = value => value.trim().replace(/\s+/g, ' ')
    const { error } = await createWebLead({ full_name: clean(form.full_name), business_name: clean(form.business_name), city: clean(form.city), business_type: clean(form.business_type), contact_phone: clean(form.contact_phone), email: clean(form.email) || null, preferred_contact: form.preferred_contact, project_type: form.project_type, needs_description: clean(form.needs_description), source: 'webs-paraguay' })
    if (error) return setState('error')
    submitted.current = true; setState('success'); trackEvent('web_lead_submitted', { projectType: form.project_type })
  }
  const field = 'w-full border-[3px] border-black bg-cream px-4 py-3 font-body focus:outline-none focus:shadow-brutal-sm'
  return <>
    <Seo title="Páginas web para negocios en Paraguay | CVitae Studio" description="Creamos páginas web rápidas y profesionales para negocios, emprendedores y profesionales de Paraguay. Web Express desde G. 550.000, sin incluir dominio." path="/webs-paraguay" jsonLd={jsonLd} />
    <div className="overflow-hidden">
      <section className="border-b-[3px] border-black bg-cream"><div className="max-w-6xl mx-auto px-4 py-16 md:py-24 grid lg:grid-cols-[1.4fr_.6fr] gap-10 items-center">
        <div><p className="font-body font-bold tracking-[.2em] text-sm text-gold">CVITAE STUDIO · WEBS PARA NEGOCIOS</p><h1 className="font-display text-5xl sm:text-7xl lg:text-8xl leading-[.9] mt-4">TU NEGOCIO MERECE ALGO MEJOR QUE SOLO REDES SOCIALES.</h1><p className="font-body text-lg md:text-xl max-w-3xl mt-6">Creamos páginas web rápidas, profesionales y adaptadas a celulares para que tus clientes encuentren tus servicios, ubicación y contacto en un solo lugar.</p><div className="flex flex-wrap gap-4 mt-8"><a href="#solicitud" onClick={() => trackEvent('request_page_click')} className="bg-black text-cream border-[3px] border-black px-6 py-4 font-bold shadow-brutal-gold">SOLICITAR MI PÁGINA</a><Link to="/portfolio/demo-climatizacion" onClick={() => trackEvent('view_demo_click')} className="bg-cream border-[3px] border-black px-6 py-4 font-bold shadow-brutal">VER DEMO</Link></div></div>
        <aside className="border-[3px] border-black bg-gold p-6 shadow-brutal"><p className="font-display text-4xl">WEB EXPRESS</p><p className="font-display text-3xl mt-4">PRECIO DE LANZAMIENTO<br/>DESDE G. 550.000</p><p className="mt-5 font-body">Tres cupos iniciales. Se reserva con G. 275.000 y el saldo se abona antes de publicar la versión definitiva.</p></aside>
      </div></section>
      <section className="max-w-6xl mx-auto px-4 py-16" aria-labelledby="alcance"><h2 id="alcance" className="font-display text-5xl">QUÉ INCLUYE WEB EXPRESS</h2><div className="grid md:grid-cols-2 gap-8 mt-8"><List title="INCLUYE" items={included}/><List title="NO INCLUYE" items={excluded}/></div></section>
      <section className="bg-black text-cream border-y-[3px] border-black"><div className="max-w-6xl mx-auto px-4 py-16 grid md:grid-cols-2 gap-10"><Info title="DOMINIO" text="Web Express no incluye la compra de un dominio personalizado. Se cotiza por separado según nombre, extensión (.com, .com.py, .org u otra), disponibilidad, proveedor y renovación anual. No damos un precio fijo sin verificarlo. Siempre que sea posible, se registra a nombre y bajo control del cliente."/><Info title="HOSTING" text="La configuración y publicación inicial en Netlify o Vercel está incluida. Puede comenzarse con un plan gratuito sujeto a límites y condiciones del proveedor; no prometemos gratuidad permanente. Si el proyecto necesita un plan pago, el costo será informado y asumido por el cliente."/></div></section>
      <section className="max-w-6xl mx-auto px-4 py-16"><h2 className="font-display text-5xl">¿NECESITÁS ALGO MÁS COMPLETO?</h2><p className="text-lg max-w-3xl mt-3">También desarrollamos soluciones personalizadas. El precio aumenta según el alcance, las funciones y el tiempo necesario. Se cotizan después de conocer los requisitos.</p><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-3 mt-8">{custom.map(x => <div key={x} className="border-[3px] border-black p-4 font-bold">{x}</div>)}</div><a href="#solicitud" onClick={() => { setForm(v => ({...v, project_type:'custom_project'})); trackEvent('project_type_selected', {projectType:'custom_project'}) }} className="inline-block mt-8 bg-gold border-[3px] border-black px-6 py-4 font-bold shadow-brutal">CONTANOS QUÉ NECESITÁS</a></section>
      <section className="border-y-[3px] border-black bg-gold/20"><div className="max-w-6xl mx-auto px-4 py-16"><h2 className="font-display text-5xl">PORTFOLIO</h2><div className="grid md:grid-cols-3 gap-6 mt-8"><Project title="CVitae.lat" tag="Proyecto propio" text="Plataforma inteligente para búsqueda laboral, análisis de CV y conexión entre candidatos y oportunidades." href="https://cvitae.lat"/><Project title="CVitae Studio" tag="Proyecto propio" text="Tienda de componentes, herramientas y servicios de desarrollo digital." href="/"/><Project title="ClimaNova Paraguay" tag="Proyecto conceptual" text="Ejemplo de una página comercial moderna para una empresa paraguaya de climatización." href="/portfolio/demo-climatizacion"/></div></div></section>
      <section id="solicitud" className="max-w-4xl mx-auto px-4 py-16"><h2 className="font-display text-5xl">SOLICITÁ TU PÁGINA</h2>{state === 'success' ? <div role="status" className="mt-8 border-[3px] border-black bg-gold p-8 shadow-brutal"><h3 className="font-display text-4xl">RECIBIMOS TU SOLICITUD.</h3><p className="mt-3">Revisaremos la información de tu negocio y nos comunicaremos por el medio que elegiste.</p></div> : <form onSubmit={submit} className="grid md:grid-cols-2 gap-5 mt-8">
        <Input label="Nombre y apellido" name="full_name" value={form.full_name} onChange={change} cls={field} maxLength={120}/><Input label="Nombre del negocio" name="business_name" value={form.business_name} onChange={change} cls={field} maxLength={160}/><Input label="Ciudad" name="city" value={form.city} onChange={change} cls={field} maxLength={100}/><Input label="Rubro" name="business_type" value={form.business_type} onChange={change} cls={field} maxLength={120}/><Input label="Teléfono o WhatsApp" name="contact_phone" value={form.contact_phone} onChange={change} cls={field} minLength={6} maxLength={40}/><Input label="Correo electrónico (opcional)" name="email" type="email" required={false} value={form.email} onChange={change} cls={field} maxLength={254}/>
        <label className="font-bold">Tipo de proyecto<select name="project_type" value={form.project_type} onChange={e => {change(e); trackEvent('project_type_selected',{projectType:e.target.value})}} className={field}><option value="web_express">Web Express</option><option value="custom_project">Proyecto personalizado</option></select></label><label className="font-bold">Medio preferido<select name="preferred_contact" value={form.preferred_contact} onChange={change} className={field}><option value="whatsapp">WhatsApp</option><option value="phone">Llamada</option><option value="email">Correo electrónico</option><option value="facebook_messenger">Facebook Messenger</option></select></label>
        <label className="md:col-span-2 font-bold">Qué necesita mostrar o resolver<textarea required minLength="10" maxLength="2000" name="needs_description" value={form.needs_description} onChange={change} rows="5" className={field}/></label><div className="absolute -left-[10000px]" aria-hidden="true"><label>No completar<input tabIndex="-1" autoComplete="off" name="website" value={form.website} onChange={change}/></label></div><label className="md:col-span-2 flex gap-3 items-start"><input required type="checkbox" name="consent" checked={form.consent} onChange={change} className="mt-1 w-5 h-5"/><span>Acepto que CVitae Studio me contacte sobre esta solicitud.</span></label>{state === 'error' && <p role="alert" className="md:col-span-2 font-bold">No pudimos enviar la solicitud. Revisá los datos e intentá nuevamente.</p>}<button disabled={state==='sending'} className="md:col-span-2 bg-black text-cream border-[3px] border-black px-6 py-4 font-bold shadow-brutal-gold disabled:opacity-50">{state==='sending'?'ENVIANDO…':'ENVIAR SOLICITUD'}</button>
      </form>}</section>
      <section className="max-w-6xl mx-auto px-4 pb-16"><h2 className="font-display text-5xl">PREGUNTAS FRECUENTES</h2>{faqs.map(f => <details key={f.q} className="border-[3px] border-black p-5 mt-4"><summary className="font-bold cursor-pointer">{f.q}</summary><p className="mt-3">{f.a}</p></details>)}</section>
    </div>
  </>
}
function List({title,items}) { return <div className="border-[3px] border-black shadow-brutal"><h3 className="font-display text-3xl bg-gold border-b-[3px] border-black p-4">{title}</h3><ul className="p-5 space-y-3">{items.map(x=><li key={x}>✓ {x}</li>)}</ul></div> }
function Info({title,text}) { return <div><h2 className="font-display text-5xl text-gold">{title}</h2><p className="mt-4 leading-7">{text}</p></div> }
function Project({title,tag,text,href}) { const external=href.startsWith('http'), ownStudio=title==='CVitae Studio'; return <article className="border-[3px] border-black bg-cream p-6 shadow-brutal"><span className="bg-gold px-2 py-1 text-xs font-bold">{ownStudio?'Proyecto propio · Creado por nosotros':tag}</span><h3 className="font-display text-3xl mt-4">{title}</h3><p className="mt-3 min-h-24">{ownStudio?'Este sitio es parte de nuestro propio trabajo: una tienda y vitrina digital diseñada y desarrollada por CVitae Studio para presentar componentes, herramientas y servicios.':text}</p><a href={href} target={external?'_blank':undefined} rel={external?'noreferrer':undefined} className="font-bold underline">VER PROYECTO →</a></article> }
function Input({label,cls,required=true,...props}) { return <label className="font-bold">{label}<input required={required} minLength={required?2:undefined} className={cls} {...props}/></label> }
